cd benchmarking/cold_start

######## Starcraft ########

# ILM(GCN)
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_gnn.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --cold_perc 0.0 > meta_ablation/output_starcraft_gcn_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_gnn.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --cold_perc 0.0 > meta_ablation/output_starcraft_gcn_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_gnn.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --cold_perc 0.0 > meta_ablation/output_starcraft_gcn_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights global0 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_global0_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights global0 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_global0_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights global0 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_global0_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights global1 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_global1_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights global1 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_global1_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights global1 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_global1_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights global2 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_global2_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights global2 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_global2_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights global2 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_global2_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights sim0 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_sim0_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights sim0 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_sim0_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights sim0 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_sim0_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights sim1 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_sim1_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights sim1 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_sim1_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights sim1 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_sim1_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights sim2 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_sim2_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights sim2 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_sim2_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights sim2 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_sim2_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights diff0 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_diff0_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights diff0 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_diff0_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights diff0 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_diff0_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights diff1 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_diff1_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights diff1 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_diff1_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights diff1 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_diff1_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights diff2 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_diff2_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights diff2 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_diff2_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights diff2 --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_diff2_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights meta --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights meta --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm_faster.py --data_name starcraft --input_size 25 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights meta --cold_perc 0.0 > meta_ablation/output_starcraft_ilm_gcn_3_iterations


######## Flickr ########

# ILM(GCN)
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_gnn.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --cold_perc 0.0 > meta_ablation/output_flickr_gcn_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_gnn.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --cold_perc 0.0 > meta_ablation/output_flickr_gcn_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_gnn.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --cold_perc 0.0 > meta_ablation/output_flickr_gcn_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights global0 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_global0_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights global0 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_global0_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights global0 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_global0_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights global1 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_global1_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights global1 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_global1_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights global1 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_global1_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights global2 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_global2_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights global2 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_global2_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights global2 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_global2_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights sim0 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_sim0_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights sim0 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_sim0_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights sim0 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_sim0_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights sim1 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_sim1_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights sim1 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_sim1_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights sim1 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_sim1_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights sim2 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_sim2_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights sim2 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_sim2_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights sim2 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_sim2_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights diff0 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_diff0_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights diff0 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_diff0_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights diff0 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_diff0_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights diff1 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_diff1_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights diff1 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_diff1_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights diff1 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_diff1_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights diff2 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_diff2_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights diff2 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_diff2_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights diff2 --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_diff2_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights meta --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights meta --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name flickr --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.3 --l2 0 --num_layers 2 --hidden_channels 128 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights meta --cold_perc 0.0 > meta_ablation/output_flickr_ilm_gcn_3_iterations


######## Yelp ########

# ILM(SAGE)
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_gnn.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --cold_perc 0.0 > meta_ablation/output_yelp_sage_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_gnn.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --cold_perc 0.0 > meta_ablation/output_yelp_sage_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_gnn.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --cold_perc 0.0 > meta_ablation/output_yelp_sage_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights global0 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_global0_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights global0 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_global0_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights global0 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_global0_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights global1 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_global1_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights global1 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_global1_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights global1 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_global1_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights global2 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_global2_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights global2 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_global2_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights global2 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_global2_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights sim0 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_sim0_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights sim0 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_sim0_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights sim0 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_sim0_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights sim1 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_sim1_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights sim1 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_sim1_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights sim1 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_sim1_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights sim2 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_sim2_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights sim2 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_sim2_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights sim2 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_sim2_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights diff0 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_diff0_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights diff0 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_diff0_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights diff0 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_diff0_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights diff1 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_diff1_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights diff1 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_diff1_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights diff1 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_diff1_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights diff2 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_diff2_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights diff2 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_diff2_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights diff2 --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_diff2_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights meta --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights meta --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name yelp --input_size 300 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-7 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights meta --cold_perc 0.0 > meta_ablation/output_yelp_ilm_sage_3_iterations


######## CSMDDI ########

# ILM(SAGE)
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_gnn.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --cold_perc 0.0 > meta_ablation/output_csmddi_sage_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_gnn.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --cold_perc 0.0 > meta_ablation/output_csmddi_sage_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_gnn.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --cold_perc 0.0 > meta_ablation/output_csmddi_sage_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights global0 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_global0_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights global0 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_global0_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights global0 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_global0_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights global1 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_global1_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights global1 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_global1_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights global1 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_global1_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights global2 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_global2_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights global2 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_global2_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights global2 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_global2_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights sim0 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_sim0_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights sim0 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_sim0_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights sim0 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_sim0_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights sim1 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_sim1_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights sim1 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_sim1_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights sim1 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_sim1_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights sim2 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_sim2_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights sim2 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_sim2_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights sim2 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_sim2_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights diff0 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_diff0_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights diff0 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_diff0_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights diff0 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_diff0_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights diff1 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_diff1_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights diff1 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_diff1_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights diff1 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_diff1_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights diff2 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_diff2_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights diff2 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_diff2_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights diff2 --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_diff2_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights meta --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights meta --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name csmddi --input_size 1493 --gnn_model SAGE --lr 0.001 --dropout 0.3 --l2 1e-4 --num_layers 2 --hidden_channels 256 --num_layers_predictor 2 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights meta --cold_perc 0.0 > meta_ablation/output_csmddi_ilm_sage_3_iterations


######## Pubmed ########

# ILM(GCN)
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_gnn.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --cold_perc 0.0 > meta_ablation/output_pubmed_gcn_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_gnn.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --cold_perc 0.0 > meta_ablation/output_pubmed_gcn_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_gnn.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --cold_perc 0.0 > meta_ablation/output_pubmed_gcn_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights global0 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_global0_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights global0 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_global0_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights global0 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_global0_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights global1 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_global1_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights global1 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_global1_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights global1 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_global1_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights global2 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_global2_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights global2 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_global2_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights global2 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_global2_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights sim0 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_sim0_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights sim0 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_sim0_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights sim0 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_sim0_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights sim1 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_sim1_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights sim1 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_sim1_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights sim1 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_sim1_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights sim2 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_sim2_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights sim2 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_sim2_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights sim2 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_sim2_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights diff0 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_diff0_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights diff0 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_diff0_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights diff0 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_diff0_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights diff1 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_diff1_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights diff1 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_diff1_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights diff1 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_diff1_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights diff2 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_diff2_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights diff2 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_diff2_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights diff2 --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_diff2_3_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 1 --weights meta --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_1_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 2 --weights meta --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_2_iterations
CUBLAS_WORKSPACE_CONFIG=:4096:8 python main_cold_ilm.py --data_name pubmed --input_size 500 --gnn_model GCN --lr 0.001 --dropout 0.1 --l2 0 --num_layers 2 --hidden_channels 256 --num_layers_predictor 3 --epochs 9999 --kill_cnt 3 --eval_steps 5 --runs 10 --iterations 3 --weights meta --cold_perc 0.0 > meta_ablation/output_pubmed_ilm_gcn_3_iterations